name: actions

on: 
  push:
    branches: [ main, develop ]

jobs:

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - working-directory: backend
      - run: python -m pip install --upgrade pip
      - run: pip install uv==0.7.3
      - run: uv venv && uv sync --frozen
      - run: ruff check --select I --fix .
      - run: ruff check .

  typing:
    needs: [ linter ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - working-directory: backend
      - run: python -m pip install --upgrade pip
      - run: pip install uv==0.7.3
      - run: uv venv && uv sync --frozen
      - run: mypy .

  tests:
    needs: [ typing, linter ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - working-directory: backend
      - run: python -m pip install --upgrade pip
      - run: pip install uv==0.7.3
      - run: uv venv && uv sync --frozen
      - run: pytest tests
